// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Room.Me.Data;

#nullable disable

namespace Room.Me.Migrations
{
    [DbContext(typeof(RoomMeDbContext))]
    [Migration("20260104031305_UpdateRooms")]
    partial class UpdateRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Room.Me.Data.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Preferences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "personality",
                            Label = "Extrovertido",
                            Value = "extrovert"
                        },
                        new
                        {
                            Id = 2,
                            Category = "personality",
                            Label = "Ambivertido",
                            Value = "ambivert"
                        },
                        new
                        {
                            Id = 3,
                            Category = "personality",
                            Label = "Introvertido",
                            Value = "introvert"
                        },
                        new
                        {
                            Id = 4,
                            Category = "schedule",
                            Label = "Madrugador",
                            Value = "early_bird"
                        },
                        new
                        {
                            Id = 5,
                            Category = "schedule",
                            Label = "Horario Flexible",
                            Value = "flexible"
                        },
                        new
                        {
                            Id = 6,
                            Category = "schedule",
                            Label = "Nocturno",
                            Value = "night_owl"
                        },
                        new
                        {
                            Id = 7,
                            Category = "cleanliness",
                            Label = "Super Ordenado",
                            Value = "neat"
                        },
                        new
                        {
                            Id = 8,
                            Category = "cleanliness",
                            Label = "Orden Normal",
                            Value = "average"
                        },
                        new
                        {
                            Id = 9,
                            Category = "cleanliness",
                            Label = "Desordenado",
                            Value = "messy"
                        },
                        new
                        {
                            Id = 10,
                            Category = "pets",
                            Label = "Tengo Mascotas",
                            Value = "has_pets"
                        },
                        new
                        {
                            Id = 11,
                            Category = "pets",
                            Label = "Acepto Mascotas",
                            Value = "ok_with"
                        },
                        new
                        {
                            Id = 12,
                            Category = "pets",
                            Label = "Cero Mascotas",
                            Value = "none"
                        },
                        new
                        {
                            Id = 13,
                            Category = "visits",
                            Label = "Casa de Fiesta",
                            Value = "party_house"
                        },
                        new
                        {
                            Id = 14,
                            Category = "visits",
                            Label = "Visitas Moderadas",
                            Value = "occasional"
                        },
                        new
                        {
                            Id = 15,
                            Category = "visits",
                            Label = "Sin Visitas",
                            Value = "private"
                        },
                        new
                        {
                            Id = 16,
                            Category = "habits",
                            Label = "Fumador",
                            Value = "smoker"
                        },
                        new
                        {
                            Id = 17,
                            Category = "habits",
                            Label = "Fumo afuera",
                            Value = "outside_only"
                        },
                        new
                        {
                            Id = 18,
                            Category = "habits",
                            Label = "No fumador",
                            Value = "non_smoker"
                        });
                });

            modelBuilder.Entity("Room.Me.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CodeExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Room.Me.Data.UserPreference", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PreferenceId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PreferenceId");

                    b.HasIndex("PreferenceId");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("Room.Me.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feature");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Servicios y Conectividad",
                            Key = "wifi",
                            Name = "Internet / Wifi"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Servicios y Conectividad",
                            Key = "agua_caliente",
                            Name = "Agua caliente"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Servicios y Conectividad",
                            Key = "servicios_basicos",
                            Name = "Servicios básicos incluidos (Luz/Agua/Gas)"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Servicios y Conectividad",
                            Key = "limpieza_comun",
                            Name = "Limpieza de áreas comunes"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Servicios y Conectividad",
                            Key = "seguridad_24h",
                            Name = "Portería / Seguridad 24h"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Servicios y Conectividad",
                            Key = "ascensor",
                            Name = "Ascensor"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Servicios y Conectividad",
                            Key = "bodega",
                            Name = "Bodega"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "terraza",
                            Name = "Terraza / Rooftop"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "bbq",
                            Name = "Zona BBQ / Parrilla"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "piscina",
                            Name = "Piscina"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "sauna",
                            Name = "Sauna / Turco"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "jacuzzi",
                            Name = "Hidromasaje / Jacuzzi"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "canchas",
                            Name = "Canchas deportivas"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "sala_eventos",
                            Name = "Sala comunal / Eventos"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "gimnasio",
                            Name = "Gimnasio"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "sala_tv",
                            Name = "Sala de TV / Cine"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "jardin",
                            Name = "Jardín interior"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Áreas Sociales y Bienestar",
                            Key = "suite_huespedes",
                            Name = "Suite de Huéspedes"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Equipamiento del Hogar",
                            Key = "linea_blanca",
                            Name = "Línea Blanca Completa"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Equipamiento del Hogar",
                            Key = "microondas",
                            Name = "Microondas"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Equipamiento del Hogar",
                            Key = "lavadora",
                            Name = "Lavadora"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Equipamiento del Hogar",
                            Key = "secadora",
                            Name = "Secadora"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Equipamiento del Hogar",
                            Key = "pequenos_electro",
                            Name = "Pequeños Electrodomésticos"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Equipamiento del Hogar",
                            Key = "menaje_cocina",
                            Name = "Menaje de Cocina"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Equipamiento del Hogar",
                            Key = "tv_sala",
                            Name = "TV en sala (Smart TV)"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Equipamiento del Hogar",
                            Key = "sala_comedor",
                            Name = "Sala y Comedor amoblados"
                        });
                });

            modelBuilder.Entity("Room.Me.Models.RoomFeature", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("RoomId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("RoomFeatures");
                });

            modelBuilder.Entity("Room.Me.Models.RoomRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("RuleId")
                        .HasColumnType("int");

                    b.Property<bool>("Value")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("RuleId");

                    b.ToTable("RoomRules");
                });

            modelBuilder.Entity("Room.Me.Models.Rooms", b =>
                {
                    b.Property<int>("IdRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoom"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUserHost")
                        .HasColumnType("int");

                    b.Property<float>("Latitud")
                        .HasColumnType("real");

                    b.Property<float>("Longitud")
                        .HasColumnType("real");

                    b.Property<float>("M2Space")
                        .HasColumnType("real");

                    b.Property<bool>("NearCollege")
                        .HasColumnType("bit");

                    b.Property<bool>("NearTransport")
                        .HasColumnType("bit");

                    b.Property<int>("NumOfBathrooms")
                        .HasColumnType("int");

                    b.Property<int>("NumOfParkingSpaces")
                        .HasColumnType("int");

                    b.Property<int>("NumOfRooms")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<bool>("State")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoom");

                    b.HasIndex("IdUserHost");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Rules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsMandatory = true,
                            Name = "Fumar"
                        },
                        new
                        {
                            Id = 2,
                            IsMandatory = true,
                            Name = "Mascotas"
                        },
                        new
                        {
                            Id = 3,
                            IsMandatory = true,
                            Name = "Visitas"
                        },
                        new
                        {
                            Id = 4,
                            IsMandatory = true,
                            Name = "Reuniones"
                        },
                        new
                        {
                            Id = 5,
                            IsMandatory = true,
                            Name = "Alcohol"
                        });
                });

            modelBuilder.Entity("Room.Me.Data.UserPreference", b =>
                {
                    b.HasOne("Room.Me.Data.Preference", "Preference")
                        .WithMany("UserPreferences")
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Room.Me.Data.User", "User")
                        .WithMany("UserPreferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preference");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Room.Me.Models.RoomFeature", b =>
                {
                    b.HasOne("Room.Me.Models.Feature", "Feature")
                        .WithMany("RoomFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Room.Me.Models.Rooms", "Room")
                        .WithMany("RoomFeatures")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Room.Me.Models.RoomRule", b =>
                {
                    b.HasOne("Room.Me.Models.Rooms", "Room")
                        .WithMany("RoomRule")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rule", "Rule")
                        .WithMany("RoomRules")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Room.Me.Models.Rooms", b =>
                {
                    b.HasOne("Room.Me.Data.User", "user")
                        .WithMany()
                        .HasForeignKey("IdUserHost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Room.Me.Data.Preference", b =>
                {
                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Room.Me.Data.User", b =>
                {
                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Room.Me.Models.Feature", b =>
                {
                    b.Navigation("RoomFeatures");
                });

            modelBuilder.Entity("Room.Me.Models.Rooms", b =>
                {
                    b.Navigation("RoomFeatures");

                    b.Navigation("RoomRule");
                });

            modelBuilder.Entity("Rule", b =>
                {
                    b.Navigation("RoomRules");
                });
#pragma warning restore 612, 618
        }
    }
}
